#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# HomeLabHub Linode StackScript / User Data
# ═══════════════════════════════════════════════════════════════════════════
# 
# Use this script as Linode User Data or StackScript to automatically
# provision a new Linode with HomeLabHub pre-installed.
#
# StackScript UDF Variables:
# <UDF name="admin_password" label="Dashboard Admin Password" />
# <UDF name="openai_key" label="OpenAI API Key (optional)" default="" />
# <UDF name="discord_token" label="Discord Bot Token (optional)" default="" />
# <UDF name="discord_client_id" label="Discord Client ID (optional)" default="" />
# <UDF name="primary_domain" label="Primary Domain" default="example.com" />
# <UDF name="install_monitoring" label="Install Monitoring Stack" oneOf="yes,no" default="no" />

set -euo pipefail

# Logging
exec > >(tee /var/log/homelab-userdata.log) 2>&1
echo "=== HomeLabHub Linode Bootstrap Started: $(date) ==="

# Variables (from UDF or defaults)
ADMIN_PASSWORD="${admin_password:-$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)}"
OPENAI_KEY="${openai_key:-}"
DISCORD_TOKEN="${discord_token:-}"
DISCORD_CLIENT_ID="${discord_client_id:-}"
PRIMARY_DOMAIN="${primary_domain:-example.com}"
INSTALL_MONITORING="${install_monitoring:-no}"

INSTALL_DIR="/opt/homelab"
REPO_URL="https://github.com/ScarletRedJoker/HomeLabHub.git"

# Helper functions
log() { echo "[$(date '+%H:%M:%S')] $*"; }

generate_secret() {
    openssl rand -base64 48 | tr -d '/+=' | head -c 32
}

generate_hex() {
    openssl rand -hex 32
}

# System updates
log "Updating system packages..."
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

# Install dependencies
log "Installing dependencies..."
apt-get install -y curl git jq ufw

# Install Docker
log "Installing Docker..."
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
fi

# Install Tailscale
log "Installing Tailscale..."
if ! command -v tailscale &>/dev/null; then
    curl -fsSL https://tailscale.com/install.sh | sh
fi

# Configure firewall
log "Configuring firewall..."
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
echo "y" | ufw enable

# Create directories
log "Creating installation directories..."
mkdir -p "$INSTALL_DIR"/{logs,workspace,postgres-init}

# Clone repository
log "Cloning HomeLabHub repository..."
git clone "$REPO_URL" "$INSTALL_DIR/HomeLabHub"

# Create symlinks
ln -sfn "$INSTALL_DIR/HomeLabHub/services" "$INSTALL_DIR/services"

# Copy configs
cp "$INSTALL_DIR/HomeLabHub/deploy/linode/docker-compose.yml" "$INSTALL_DIR/"
cp "$INSTALL_DIR/HomeLabHub/deploy/linode/Caddyfile" "$INSTALL_DIR/"

# Generate all secrets
POSTGRES_PASSWORD=$(generate_secret)
JARVIS_DB_PASSWORD=$(generate_secret)
DISCORD_DB_PASSWORD=$(generate_secret)
STREAMBOT_DB_PASSWORD=$(generate_secret)
SESSION_SECRET=$(generate_hex)
SECRET_KEY=$(generate_hex)
DISCORD_SESSION_SECRET=$(generate_hex)
STREAMBOT_SESSION_SECRET=$(generate_hex)
SERVICE_AUTH_TOKEN=$(generate_hex)
CODE_SERVER_PASSWORD=$(generate_secret)
N8N_PASSWORD=$(generate_secret)
GRAFANA_PASSWORD=$(generate_secret)

# Write environment file
log "Writing environment configuration..."
cat > "$INSTALL_DIR/.env" << EOF
# ══════════════════════════════════════════════════════════════
# HomeLabHub Environment - Auto-generated by Linode StackScript
# Generated: $(date)
# ══════════════════════════════════════════════════════════════

# Database Passwords
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JARVIS_DB_PASSWORD=${JARVIS_DB_PASSWORD}
DISCORD_DB_PASSWORD=${DISCORD_DB_PASSWORD}
STREAMBOT_DB_PASSWORD=${STREAMBOT_DB_PASSWORD}

# Session Secrets
SESSION_SECRET=${SESSION_SECRET}
SECRET_KEY=${SECRET_KEY}
DISCORD_SESSION_SECRET=${DISCORD_SESSION_SECRET}
STREAMBOT_SESSION_SECRET=${STREAMBOT_SESSION_SECRET}
SERVICE_AUTH_TOKEN=${SERVICE_AUTH_TOKEN}

# Admin Credentials
WEB_USERNAME=admin
WEB_PASSWORD=${ADMIN_PASSWORD}
CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD}
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}

# API Keys
OPENAI_API_KEY=${OPENAI_KEY}

# Discord
DISCORD_BOT_TOKEN=${DISCORD_TOKEN}
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
DISCORD_CLIENT_SECRET=
DISCORD_APP_ID=${DISCORD_CLIENT_ID}
VITE_DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}

# Domain
PRIMARY_DOMAIN=${PRIMARY_DOMAIN}

# Monitoring
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

# System
TZ=America/New_York
PUID=1000
PGID=1000
EOF

chmod 600 "$INSTALL_DIR/.env"

# PostgreSQL init script
log "Creating PostgreSQL init script..."
cat > "$INSTALL_DIR/postgres-init/00-init-all-databases.sh" << 'SCRIPT'
#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ticketbot WITH PASSWORD '${DISCORD_DB_PASSWORD}';
    CREATE USER streambot WITH PASSWORD '${STREAMBOT_DB_PASSWORD}';
    CREATE USER jarvis WITH PASSWORD '${JARVIS_DB_PASSWORD}';
    CREATE DATABASE ticketbot OWNER ticketbot;
    CREATE DATABASE streambot OWNER streambot;
    CREATE DATABASE homelab_jarvis OWNER jarvis;
    GRANT ALL PRIVILEGES ON DATABASE ticketbot TO ticketbot;
    GRANT ALL PRIVILEGES ON DATABASE streambot TO streambot;
    GRANT ALL PRIVILEGES ON DATABASE homelab_jarvis TO jarvis;
EOSQL
SCRIPT
chmod +x "$INSTALL_DIR/postgres-init/00-init-all-databases.sh"

# Determine services to start
SERVICES="caddy redis homelab-postgres homelab-dashboard homelab-celery-worker n8n code-server code-server-proxy scarletredjoker-web rig-city-site"

if [[ -n "$DISCORD_TOKEN" ]]; then
    SERVICES+=" discord-bot"
fi

if [[ "$INSTALL_MONITORING" == "yes" ]]; then
    SERVICES+=" homelab-prometheus homelab-grafana homelab-loki homelab-node-exporter homelab-cadvisor"
fi

# Deploy services
log "Deploying services: $SERVICES"
cd "$INSTALL_DIR"
docker compose pull $SERVICES || true
docker compose build $SERVICES || true
docker compose up -d $SERVICES

# Wait for services
log "Waiting for services to initialize..."
sleep 60

# Final status
log "Checking service status..."
docker compose ps

# Create MOTD
cat > /etc/motd << 'MOTD'
═══════════════════════════════════════════════════════════════════
                    HOMELAB HUB SERVER
═══════════════════════════════════════════════════════════════════

Your HomeLabHub instance is ready!

Quick Commands:
  cd /opt/homelab
  docker compose logs -f          # View logs
  docker compose ps               # Check status
  ./HomeLabHub/homelab status     # Full status

Services:
  Dashboard:   https://dash.YOUR_DOMAIN
  Code Server: https://code.YOUR_DOMAIN
  N8N:         https://n8n.YOUR_DOMAIN

Next Steps:
  1. Run: sudo tailscale up
  2. Update DNS records for your domain
  3. Check credentials in /opt/homelab/.env

═══════════════════════════════════════════════════════════════════
MOTD

# Save credentials to a secure file
cat > /root/.homelab-credentials << EOF
HomeLabHub Credentials (KEEP SECURE!)
Generated: $(date)
═══════════════════════════════════════

Dashboard:
  URL: https://dash.${PRIMARY_DOMAIN}
  Username: admin
  Password: ${ADMIN_PASSWORD}

Code Server:
  URL: https://code.${PRIMARY_DOMAIN}
  Password: ${CODE_SERVER_PASSWORD}

N8N:
  URL: https://n8n.${PRIMARY_DOMAIN}
  Username: admin
  Password: ${N8N_PASSWORD}

Grafana (if installed):
  URL: https://grafana.${PRIMARY_DOMAIN}
  Username: admin
  Password: ${GRAFANA_PASSWORD}

PostgreSQL:
  Host: localhost (or homelab-postgres in Docker)
  Superuser Password: ${POSTGRES_PASSWORD}

Full config: /opt/homelab/.env
EOF
chmod 600 /root/.homelab-credentials

log "=== HomeLabHub Bootstrap Complete ==="
log "Credentials saved to: /root/.homelab-credentials"
echo ""
echo "View credentials: sudo cat /root/.homelab-credentials"
