name: Uptime Kuma
description: Self-hosted monitoring tool like Uptime Robot
category: monitoring
icon: uptime-kuma
version: latest
author: Louis Lam
requires:
  - persistent_storage

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - uptime-kuma:/app/data
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.${DOMAIN}`)"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
    restart: unless-stopped

volumes:
  uptime-kuma:

networks:
  homelab:
    external: true
