#!/bin/bash
#
# Home Assistant Bootstrap & Provisioning Script
# Zero-touch configuration for Home Assistant integration with Jarvis Homelab
#
# This script:
# - Detects Docker network CIDR automatically
# - Generates configuration files with proper reverse proxy settings
# - Provisions secrets and API tokens
# - Sets correct permissions for Home Assistant
# - Registers with Jarvis dashboard for health monitoring
# - Is idempotent (safe to run multiple times)
#
# Usage: ./scripts/bootstrap-homeassistant.sh
#
# Author: Homelab Team
# Last Updated: 2025-11-15

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
HA_CONFIG_DIR="${PROJECT_ROOT}/volumes/homeassistant"
HA_DOCKER_CONFIG_DIR="${PROJECT_ROOT}/config/homeassistant"
COMPOSE_FILE="${PROJECT_ROOT}/docker-compose.unified.yml"
ENV_FILE="${PROJECT_ROOT}/.env"

# Home Assistant defaults
HA_USER_ID=1000
HA_GROUP_ID=1000
HA_API_KEY_LENGTH=64

# Logging
log_info() {
    echo -e "${CYAN}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

log_step() {
    echo ""
    echo -e "${BOLD}${BLUE}━━━ $* ━━━${NC}"
}

# Function to generate secure random string
generate_secure_key() {
    local length="${1:-64}"
    openssl rand -base64 $((length * 3 / 4)) | tr -d '\n' | head -c "$length"
}

# Function to detect Docker network CIDR
detect_docker_network_cidr() {
    log_step "Detecting Docker Network Configuration"
    
    local network_name="homelab"
    
    # Check if network exists
    if docker network inspect "$network_name" &>/dev/null; then
        local cidr
        cidr=$(docker network inspect "$network_name" -f '{{range .IPAM.Config}}{{.Subnet}}{{end}}' 2>/dev/null || echo "")
        
        if [[ -n "$cidr" ]]; then
            log_success "Detected Docker network '$network_name' with CIDR: $cidr"
            echo "$cidr"
            return 0
        fi
    fi
    
    # Network doesn't exist or doesn't have CIDR - use default ranges
    log_warn "Docker network '$network_name' not found or not configured"
    log_info "Using default Docker network ranges"
    echo "172.16.0.0/12"
}

# Function to create directory structure
create_directory_structure() {
    log_step "Creating Directory Structure"
    
    # Create main config directory
    mkdir -p "$HA_CONFIG_DIR"
    log_info "Created directory: $HA_CONFIG_DIR"
    
    # Create subdirectories
    local subdirs=(
        "custom_components"
        "themes"
        "www"
        "blueprints/automation"
        "blueprints/script"
        "tts"
        "deps"
    )
    
    for dir in "${subdirs[@]}"; do
        mkdir -p "$HA_CONFIG_DIR/$dir"
        log_info "Created directory: $HA_CONFIG_DIR/$dir"
    done
    
    log_success "Directory structure created"
}

# Function to generate configuration.yaml
generate_configuration_yaml() {
    log_step "Generating configuration.yaml"
    
    local config_file="$HA_CONFIG_DIR/configuration.yaml"
    local docker_cidr
    docker_cidr=$(detect_docker_network_cidr)
    
    # Check if file exists and has custom modifications
    if [[ -f "$config_file" ]]; then
        if grep -q "# USER_MODIFIED" "$config_file" 2>/dev/null; then
            log_warn "Configuration file exists with user modifications - skipping regeneration"
            log_info "To regenerate, remove '# USER_MODIFIED' comment from $config_file"
            return 0
        fi
    fi
    
    # Generate new configuration
    cat > "$config_file" <<EOF
# Home Assistant Core Configuration
# Auto-generated by bootstrap-homeassistant.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# To prevent automatic regeneration, add this comment: # USER_MODIFIED

# Load default integrations
default_config:

# Configure HTTP access for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ${docker_cidr}
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 10.0.0.0/8
  ip_ban_enabled: false
  login_attempts_threshold: 10
  
# Frontend configuration
frontend:
  themes: !include_dir_merge_named themes

# Enable configuration UI
config:

# Enable history tracking
history:

# Enable logbook
logbook:

# Enable system health monitoring
system_health:

# Recorder (database) configuration
recorder:
  purge_keep_days: 7
  commit_interval: 1
  db_url: !secret db_url

# Logger configuration
logger:
  default: info
  logs:
    homeassistant.core: info
    homeassistant.components.http: warn

# Text to speech
tts:
  - platform: google_translate
    language: 'en'

# Automation loading
automation: !include automations.yaml

# Script loading
script: !include scripts.yaml

# Scene loading
scene: !include scenes.yaml

# RESTful integration for Jarvis Dashboard
rest_command:
  jarvis_health_check:
    url: "http://homelab-dashboard:5000/api/jarvis/health/homeassistant"
    method: POST
    headers:
      Content-Type: "application/json"
      X-API-Key: "!secret jarvis_api_key"
    payload: '{"status": "{{ status }}", "message": "{{ message }}"}'
  
  jarvis_deploy_request:
    url: "http://homelab-dashboard:5000/api/jarvis/voice/deploy"
    method: POST
    headers:
      Content-Type: "application/json"
      X-API-Key: "!secret jarvis_api_key"
    payload: '{"command": "{{ command }}", "params": {{ params | tojson }}}'

# Jarvis Dashboard Health Monitoring
sensor:
  - platform: rest
    name: "Jarvis Homelab Status"
    resource: "http://homelab-dashboard:5000/api/jarvis/status"
    scan_interval: 60
    headers:
      X-API-Key: "!secret jarvis_api_key"
    json_attributes:
      - active_deployments
      - total_services
      - healthy_services
    value_template: '{{ value_json.status | default("unknown") }}'
    
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

# Enable Prometheus metrics for Jarvis monitoring
prometheus:
  namespace: homeassistant

# Enable API for Jarvis integration
api:

# Enable webhook support
webhook:
EOF

    log_success "Configuration file generated: $config_file"
}

# Function to generate secrets.yaml
generate_secrets_yaml() {
    log_step "Generating secrets.yaml"
    
    local secrets_file="$HA_CONFIG_DIR/secrets.yaml"
    
    # Check if file exists
    if [[ -f "$secrets_file" ]]; then
        log_warn "Secrets file already exists - checking for required keys"
        
        # Ensure required keys exist
        if ! grep -q "jarvis_api_key:" "$secrets_file"; then
            log_info "Adding missing jarvis_api_key"
            local jarvis_key
            jarvis_key=$(generate_secure_key 32)
            echo "" >> "$secrets_file"
            echo "# Jarvis Dashboard API Key (auto-generated)" >> "$secrets_file"
            echo "jarvis_api_key: $jarvis_key" >> "$secrets_file"
        fi
        
        if ! grep -q "db_url:" "$secrets_file"; then
            log_info "Adding missing db_url"
            echo "" >> "$secrets_file"
            echo "# Internal SQLite database (default)" >> "$secrets_file"
            echo "db_url: sqlite:////config/home-assistant_v2.db" >> "$secrets_file"
        fi
        
        return 0
    fi
    
    # Generate new secrets file
    local jarvis_key
    jarvis_key=$(generate_secure_key 32)
    
    cat > "$secrets_file" <<EOF
# Home Assistant Secrets
# Auto-generated by bootstrap-homeassistant.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# WARNING: Keep this file secure! Do not commit to version control.
# These secrets are used for API authentication and service integration.

# Jarvis Dashboard API Key
# Used for RESTful API calls to Jarvis dashboard
jarvis_api_key: $jarvis_key

# Database URL (SQLite by default)
# For PostgreSQL: postgresql://user:password@host:port/database
db_url: sqlite:////config/home-assistant_v2.db

# Latitude and Longitude for weather and sun tracking
# Update these with your actual location
home_latitude: 0.0
home_longitude: 0.0

# Elevation above sea level in meters
home_elevation: 0

# Time zone (automatically set by container)
time_zone: America/New_York
EOF

    log_success "Secrets file generated: $secrets_file"
    log_warn "Please update latitude, longitude, and elevation in secrets.yaml"
    
    # Store Jarvis API key in .env for dashboard integration
    if [[ -f "$ENV_FILE" ]]; then
        if ! grep -q "HOME_ASSISTANT_API_KEY=" "$ENV_FILE"; then
            echo "" >> "$ENV_FILE"
            echo "# Home Assistant Jarvis API Key (auto-generated)" >> "$ENV_FILE"
            echo "HOME_ASSISTANT_API_KEY=$jarvis_key" >> "$ENV_FILE"
            log_info "Jarvis API key stored in .env file"
        fi
    fi
}

# Function to create empty configuration files
create_empty_configs() {
    log_step "Creating Empty Configuration Files"
    
    local files=(
        "automations.yaml"
        "scripts.yaml"
        "scenes.yaml"
    )
    
    for file in "${files[@]}"; do
        local filepath="$HA_CONFIG_DIR/$file"
        if [[ ! -f "$filepath" ]]; then
            echo "# Home Assistant ${file%.yaml} configuration" > "$filepath"
            echo "# Auto-generated by bootstrap-homeassistant.sh" >> "$filepath"
            echo "" >> "$filepath"
            log_info "Created: $filepath"
        else
            log_info "Already exists: $filepath"
        fi
    done
    
    log_success "Empty configuration files ready"
}

# Function to set proper permissions
set_permissions() {
    log_step "Setting File Permissions"
    
    # Set ownership to Home Assistant user (1000:1000)
    log_info "Setting ownership to ${HA_USER_ID}:${HA_GROUP_ID}"
    chown -R ${HA_USER_ID}:${HA_GROUP_ID} "$HA_CONFIG_DIR" 2>/dev/null || {
        log_warn "Cannot set ownership (may require sudo)"
        log_info "Run manually: sudo chown -R ${HA_USER_ID}:${HA_GROUP_ID} $HA_CONFIG_DIR"
    }
    
    # Set directory permissions to 755
    find "$HA_CONFIG_DIR" -type d -exec chmod 755 {} \; 2>/dev/null || {
        log_warn "Cannot set directory permissions (may require sudo)"
    }
    
    # Set file permissions to 644
    find "$HA_CONFIG_DIR" -type f -exec chmod 644 {} \; 2>/dev/null || {
        log_warn "Cannot set file permissions (may require sudo)"
    }
    
    # Set secrets.yaml to 600 for security
    if [[ -f "$HA_CONFIG_DIR/secrets.yaml" ]]; then
        chmod 600 "$HA_CONFIG_DIR/secrets.yaml" 2>/dev/null || {
            log_warn "Cannot set secrets.yaml permissions (may require sudo)"
        }
        log_info "Secured secrets.yaml with 600 permissions"
    fi
    
    log_success "Permissions configured"
}

# Function to register with Jarvis dashboard
register_with_jarvis() {
    log_step "Registering with Jarvis Dashboard"
    
    # Check if dashboard is running
    if ! docker ps --format '{{.Names}}' | grep -q '^homelab-dashboard$'; then
        log_warn "Jarvis dashboard not running - skipping registration"
        log_info "Registration will happen automatically when dashboard starts"
        return 0
    fi
    
    # Attempt registration
    local jarvis_url="http://localhost:5000/api/jarvis/health/register"
    local api_key
    
    if [[ -f "$HA_CONFIG_DIR/secrets.yaml" ]]; then
        api_key=$(grep "jarvis_api_key:" "$HA_CONFIG_DIR/secrets.yaml" | cut -d':' -f2 | tr -d ' ')
    fi
    
    if [[ -n "$api_key" ]]; then
        log_info "Attempting to register Home Assistant with Jarvis..."
        
        curl -s -X POST "$jarvis_url" \
            -H "Content-Type: application/json" \
            -H "X-API-Key: $api_key" \
            -d '{
                "service": "homeassistant",
                "url": "http://homeassistant:8123",
                "health_endpoint": "/api/",
                "description": "Smart Home Automation Hub"
            }' &>/dev/null && {
            log_success "Registered with Jarvis dashboard"
        } || {
            log_warn "Could not register with Jarvis (will retry automatically)"
        }
    else
        log_warn "No API key found - skipping registration"
    fi
}

# Function to create .gitignore
create_gitignore() {
    log_step "Creating .gitignore for Home Assistant"
    
    local gitignore_file="$HA_CONFIG_DIR/.gitignore"
    
    cat > "$gitignore_file" <<'EOF'
# Home Assistant .gitignore
# Keep configuration in version control, but protect secrets

# Secrets and sensitive data
secrets.yaml
*.db
*.db-shm
*.db-wal
*.log
*.pid

# Generated files
*.pyc
__pycache__/
.cloud/
.storage/
deps/
tts/

# Temporary files
*.tmp
*.bak
*.swp
*.swo
*~

# OS files
.DS_Store
Thumbs.db

# IDE files
.vscode/
.idea/

# Home Assistant specific
home-assistant_v2.db*
home-assistant.log*
OZW_Log.txt
ip_bans.yaml
.google.token
.uuid

# Keep these configuration files
!configuration.yaml
!automations.yaml
!scripts.yaml
!scenes.yaml
!groups.yaml
!customize.yaml
EOF

    log_success "Created .gitignore"
}

# Function to validate configuration
validate_configuration() {
    log_step "Validating Configuration"
    
    local errors=0
    
    # Check if required files exist
    local required_files=(
        "configuration.yaml"
        "secrets.yaml"
        "automations.yaml"
        "scripts.yaml"
        "scenes.yaml"
    )
    
    for file in "${required_files[@]}"; do
        if [[ -f "$HA_CONFIG_DIR/$file" ]]; then
            log_success "✓ $file exists"
        else
            log_error "✗ $file missing"
            ((errors++))
        fi
    done
    
    # Check directory permissions
    if [[ -d "$HA_CONFIG_DIR" ]]; then
        log_success "✓ Config directory exists"
    else
        log_error "✗ Config directory missing"
        ((errors++))
    fi
    
    if [[ $errors -eq 0 ]]; then
        log_success "Configuration validation passed"
        return 0
    else
        log_error "Configuration validation failed with $errors errors"
        return 1
    fi
}

# Function to display summary
display_summary() {
    echo ""
    echo -e "${BOLD}${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║                                                                ║${NC}"
    echo -e "${BOLD}${GREEN}║   🏠 Home Assistant Bootstrap Complete! ✨                    ║${NC}"
    echo -e "${BOLD}${GREEN}║                                                                ║${NC}"
    echo -e "${BOLD}${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}Configuration Directory:${NC} $HA_CONFIG_DIR"
    echo -e "${CYAN}Docker Network CIDR:${NC} $(detect_docker_network_cidr)"
    echo ""
    echo -e "${BOLD}Next Steps:${NC}"
    echo -e "  1. ${GREEN}Start Home Assistant:${NC}"
    echo -e "     ${YELLOW}docker-compose -f docker-compose.unified.yml up -d homeassistant${NC}"
    echo ""
    echo -e "  2. ${GREEN}Access Home Assistant:${NC}"
    echo -e "     ${YELLOW}https://home.evindrake.net${NC}"
    echo ""
    echo -e "  3. ${GREEN}Complete onboarding wizard${NC} (first-time setup)"
    echo ""
    echo -e "  4. ${GREEN}Update location:${NC}"
    echo -e "     Edit ${YELLOW}$HA_CONFIG_DIR/secrets.yaml${NC}"
    echo -e "     Set your latitude, longitude, and elevation"
    echo ""
    echo -e "${BOLD}Integration with Jarvis:${NC}"
    echo -e "  • Health monitoring: ${GREEN}✓ Configured${NC}"
    echo -e "  • API integration: ${GREEN}✓ Configured${NC}"
    echo -e "  • Auto-discovery: ${GREEN}✓ Enabled${NC}"
    echo ""
    echo -e "${BOLD}Troubleshooting:${NC}"
    echo -e "  • View logs: ${YELLOW}docker logs homeassistant${NC}"
    echo -e "  • Check config: ${YELLOW}docker exec homeassistant hass --script check_config${NC}"
    echo -e "  • Restart: ${YELLOW}docker restart homeassistant${NC}"
    echo ""
}

# Main execution
main() {
    echo ""
    echo -e "${BOLD}${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${CYAN}║                                                                ║${NC}"
    echo -e "${BOLD}${CYAN}║   🏠 Home Assistant Bootstrap & Provisioning Script 🚀        ║${NC}"
    echo -e "${BOLD}${CYAN}║                                                                ║${NC}"
    echo -e "${BOLD}${CYAN}║   Zero-touch configuration for Jarvis Homelab                 ║${NC}"
    echo -e "${BOLD}${CYAN}║                                                                ║${NC}"
    echo -e "${BOLD}${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    log_info "Starting Home Assistant bootstrap process..."
    log_info "Configuration directory: $HA_CONFIG_DIR"
    echo ""
    
    # Execute bootstrap steps
    create_directory_structure
    generate_configuration_yaml
    generate_secrets_yaml
    create_empty_configs
    create_gitignore
    set_permissions
    register_with_jarvis
    
    # Validate
    if validate_configuration; then
        display_summary
        exit 0
    else
        log_error "Bootstrap completed with errors"
        exit 1
    fi
}

# Run main function
main "$@"
